Repository woodpecker-ci/plugin-kaniko, pull requests merged in 2024-01, with the labels that each got.

#7 Fix release pipeline
  .woodpecker/test-release.yaml
Labels: bug, build

#9 Switch to Woodpecker Environment Variables
  plugin.sh
Labels: enhancement, breaking

#11 chore(deps): update alpine docker tag to v3.19
  Dockerfile.test
Labels: build

#12 Add `dry-run` setting and docs.mf
  docs.md
  plugin.sh
Labels: enhancement, breaking

#20 Add two new options (--ignore-var-run and env_file), review the dry-run logic and try to fix some issues
  plugin.sh
Labels: enhancement
